### ISSUE TITLE
code is miss

### ISSUE THREAD

**Issue by narayan727** [devchandansh/payment-using-paytm-codeigniter#1]
some code is miss in library folder

**Comment by devchandansh** [comment]
Do you getting Any Issue? Its is Tested Code.

**Comment by deepakdsh** [comment]
I am using your code in my project but getting some error, please check the below link for it:

https://prnt.sc/vhs6jo

Guide me how to fix it.

Thanks in advance

**Comment by devchandansh** [comment]
Please Check the CodeIgniter System Folder. May Be the File is Missing there. 
You can also Download the same CodeIgniter version and replace the System folder. Please take a backup of Previous Folder.

**Comment by devchandansh** [comment]
As It Is working fine, I am closing this Issue.
